import test from 'node:test';
import assert from 'node:assert/strict';
import { initializeApp, deleteApp } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';
import { createAiBudgetGate } from '../ai-budget.mjs';
import { createBudgetedProvider } from '../budgeted-provider.mjs';
test('atomic cap, dispatch once, unknown hold, rollover, cancellation and overrun stop', async t => {
  assert(process.env.FIRESTORE_EMULATOR_HOST);
  const app = initializeApp({ projectId: 'demo-portal' }, 'budget-test'); t.after(() => deleteApp(app));
  const db = getFirestore(app); let now = new Date('2026-10-31T14:00:00Z');
  const gate = createAiBudgetGate(db, { scope: `test-${Date.now()}`, clock: () => now, limitMicros: 100 });
  const input = operationId => ({ operationId, kind: 'ai', model: 'gemini-3.5-flash-lite', upperBoundJpyMicro: 60, pricingVersion: 'fixture', hardBoundVerified: true });
  const results = await Promise.all(['a', 'b'].map(id => gate.reserve(input(id))));
  assert.equal(results.filter(r => r.allowed).length, 1);
  const id = results[0].allowed ? 'a' : 'b';
  assert.equal((await gate.reserve(input(id))).replay, true);
  assert.deepEqual(await Promise.all([gate.claimDispatch(id), gate.claimDispatch(id)]).then(r => r.sort()), [false, true]);
  await gate.markUnknown(id); await assert.rejects(gate.cancel(id));
  assert.equal((await gate.reserve(input('c'))).allowed, false);
  now = new Date('2026-10-31T15:00:00Z');
  assert.equal((await gate.reserve(input(id))).state, 'unknown');
  assert.equal(await gate.claimDispatch(id), false);
  assert.equal((await gate.reserve(input('new-month'))).allowed, true);
  await gate.cancel('new-month');
  assert.equal((await gate.reserve(input('after-cancel'))).allowed, true);
  assert.equal((await gate.reserve({ ...input('exact-cap'), upperBoundJpyMicro: 40 })).allowed, true);
  assert.equal((await gate.reserve({ ...input('one-over'), upperBoundJpyMicro: 1 })).code, 'MONTHLY_BUDGET_EXHAUSTED');
  await gate.settle(id, 30); assert.equal((await gate.settle(id, 30)).overrun, false);
  await assert.rejects(gate.settle(id, 31));
  await gate.claimDispatch('after-cancel');
  assert.equal((await gate.settle('after-cancel', 61)).overrun, true);
  assert.equal(await gate.claimDispatch('exact-cap'), false);
  now = new Date('2026-12-01T00:00:00Z');
  assert.equal((await gate.reserve(input('after-overrun'))).code, 'COST_OVERRUN');
  await assert.rejects(gate.reserve({ ...input(id), upperBoundJpyMicro: 1 }));
  assert.equal((await gate.reserve({ ...input('no-bound'), hardBoundVerified: false })).code, 'UNVERIFIED_COST_BOUND');
  now = new Date('2026-10-31T14:59:59Z');
  const rollover = createAiBudgetGate(db, { scope: `rollover-${Date.now()}`, clock: () => now, limitMicros: 100 });
  await rollover.reserve(input('old-reserved'));
  now = new Date('2026-10-31T15:00:00Z');
  assert.equal(await rollover.claimDispatch('old-reserved'), false);
  assert.equal((await rollover.reserve(input('old-reserved'))).allowed, false);
  await rollover.cancel('old-reserved');
  assert.equal((await rollover.reserve(input('current-reserved'))).allowed, true);
  assert.equal(await rollover.claimDispatch('current-reserved'), true);
});

test('budgeted provider blocks parallel paid calls and retains unknown cost on Firestore', async t => {
  assert(process.env.FIRESTORE_EMULATOR_HOST);
  const app = initializeApp({ projectId: 'demo-portal' }, 'budget-provider-test'); t.after(() => deleteApp(app));
  const gate = createAiBudgetGate(getFirestore(app), { scope: `provider-${Date.now()}`, clock: () => new Date('2026-10-05T00:00:00Z'), limitMicros: 100 });
  const cost = { kind: 'ai', model: 'gemini-3.5-flash-lite', upperBoundJpyMicro: 60, pricingVersion: 'anonymous-fixture', hardBoundVerified: true };
  let started, finish, calls = 0;
  const dispatchStarted = new Promise(resolve => { started = resolve; });
  const hold = new Promise(resolve => { finish = resolve; });
  const call = createBudgetedProvider({ gate, prepare: async input => ({ request: input, cost }), dispatch: async () => {
    calls++; started(); await hold; throw new Error('anonymous timeout');
  } });
  const first = call({ question: '匿名質問' }, { operationId: 'first' });
  try {
    await dispatchStarted;
    assert.equal((await call({ question: '別の質問' }, { operationId: 'second' })).code, 'MONTHLY_BUDGET_EXHAUSTED');
    assert.equal((await call({ question: '匿名質問' }, { operationId: 'first' })).code, 'OPERATION_NOT_RESERVABLE');
    assert.equal((await call({ question: '変更された質問' }, { operationId: 'first' })).code, 'BUDGET_LEDGER_UNAVAILABLE');
  } finally { finish(); }
  assert.equal((await first).code, 'PROVIDER_RESULT_UNKNOWN');
  const replay = await call({ question: '匿名質問' }, { operationId: 'first' });
  assert.equal(replay.state, 'unknown');
  assert.equal(replay.fallback.history, true);
  assert.equal(calls, 1);
  await assert.rejects(gate.cancel('first'));
});
