import test from 'node:test';
import assert from 'node:assert/strict';
import { initializeApp, deleteApp } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';
import { createAiBudgetGate } from '../ai-budget.mjs';
test('atomic cap, dispatch once, unknown hold, rollover, cancellation and overrun stop', async t => {
  assert(process.env.FIRESTORE_EMULATOR_HOST);
  const app = initializeApp({ projectId: 'demo-portal' }, 'budget-test'); t.after(() => deleteApp(app));
  const db = getFirestore(app); let now = new Date('2026-10-31T14:00:00Z');
  const gate = createAiBudgetGate(db, { scope: `test-${Date.now()}`, clock: () => now, limitMicros: 100 });
  const input = operationId => ({ operationId, kind: 'ai', model: 'gemini-3.5-flash-lite', upperBoundJpyMicro: 60, pricingVersion: 'fixture', hardBoundVerified: true });
  const results = await Promise.all(['a', 'b'].map(id => gate.reserve(input(id))));
  assert.equal(results.filter(r => r.allowed).length, 1);
  const id = results[0].allowed ? 'a' : 'b';
  assert.equal((await gate.reserve(input(id))).replay, true);
  assert.deepEqual(await Promise.all([gate.claimDispatch(id), gate.claimDispatch(id)]).then(r => r.sort()), [false, true]);
  await gate.markUnknown(id); await assert.rejects(gate.cancel(id));
  assert.equal((await gate.reserve(input('c'))).allowed, false);
  now = new Date('2026-10-31T15:00:00Z');
  assert.equal((await gate.reserve(input(id))).state, 'unknown');
  assert.equal(await gate.claimDispatch(id), false);
  assert.equal((await gate.reserve(input('new-month'))).allowed, true);
  await gate.cancel('new-month');
  assert.equal((await gate.reserve(input('after-cancel'))).allowed, true);
  assert.equal((await gate.reserve({ ...input('exact-cap'), upperBoundJpyMicro: 40 })).allowed, true);
  assert.equal((await gate.reserve({ ...input('one-over'), upperBoundJpyMicro: 1 })).code, 'MONTHLY_BUDGET_EXHAUSTED');
  await gate.settle(id, 30); assert.equal((await gate.settle(id, 30)).overrun, false);
  await assert.rejects(gate.settle(id, 31));
  await gate.claimDispatch('after-cancel');
  assert.equal((await gate.settle('after-cancel', 61)).overrun, true);
  assert.equal(await gate.claimDispatch('exact-cap'), false);
  now = new Date('2026-12-01T00:00:00Z');
  assert.equal((await gate.reserve(input('after-overrun'))).code, 'COST_OVERRUN');
  await assert.rejects(gate.reserve({ ...input(id), upperBoundJpyMicro: 1 }));
  assert.equal((await gate.reserve({ ...input('no-bound'), hardBoundVerified: false })).code, 'UNVERIFIED_COST_BOUND');
  now = new Date('2026-10-31T14:59:59Z');
  const rollover = createAiBudgetGate(db, { scope: `rollover-${Date.now()}`, clock: () => now, limitMicros: 100 });
  await rollover.reserve(input('old-reserved'));
  now = new Date('2026-10-31T15:00:00Z');
  assert.equal(await rollover.claimDispatch('old-reserved'), false);
  assert.equal((await rollover.reserve(input('old-reserved'))).allowed, false);
  await rollover.cancel('old-reserved');
  assert.equal((await rollover.reserve(input('current-reserved'))).allowed, true);
  assert.equal(await rollover.claimDispatch('current-reserved'), true);
});
