import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { once } from 'node:events';
import { initializeApp, deleteApp } from 'firebase-admin/app';
import { getAuth } from 'firebase-admin/auth';
import { getFirestore } from 'firebase-admin/firestore';
import { initializeTestEnvironment, assertFails, assertSucceeds } from '@firebase/rules-unit-testing';
import { doc, setDoc, getDoc } from 'firebase/firestore';
import { createFirestoreRepository } from '../firestore.mjs';
import { createApplication } from '../application.mjs';
import { createApi } from '../http.mjs';

test('Firebase Auth, tenant isolation, rules and transactional state/audit', async t => {
  assert(process.env.FIRESTORE_EMULATOR_HOST && process.env.FIREBASE_AUTH_EMULATOR_HOST);
  const env = await initializeTestEnvironment({ projectId: 'demo-portal', firestore: { rules: await readFile(new URL('../../firestore.rules', import.meta.url), 'utf8') } });
  const app = initializeApp({ projectId: 'demo-portal' }, 'integration');
  const db = getFirestore(app); const auth = getAuth(app);
  t.after(async () => { await env.cleanup(); await deleteApp(app); });
  await env.clearFirestore();
  const signup = await fetch(`http://${process.env.FIREBASE_AUTH_EMULATOR_HOST}/identitytoolkit.googleapis.com/v1/accounts:signUp?key=fake`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: 'fixture@example.invalid', password: 'fixture-test-password', returnSecureToken: true }) });
  const token = await signup.json(); assert.equal(signup.status, 200);
  const claims = await auth.verifyIdToken(token.idToken, true); assert.equal(claims.uid, token.localId);
  await assert.rejects(auth.verifyIdToken('malformed', true));
  const owner = env.authenticatedContext('owner').firestore();
  const other = env.authenticatedContext('other').firestore();
  for (const collection of ['wishlist', 'recipes', 'books']) await assertSucceeds(setDoc(doc(owner, 'users/owner/' + collection + '/data'), { items: [] }));
  await assertFails(getDoc(doc(other, 'users/owner/books/data')));
  await assertFails(setDoc(doc(owner, 'users/owner/books/arbitrary'), {}));
  for (const collection of ['sources', 'purchaseOrders', 'purchaseLines', 'products', 'productStates', 'userObservations', 'auditLogs', 'identityKeys', 'replenishmentEstimates', 'recommendations']) {
    await assertFails(setDoc(doc(owner, `users/owner/${collection}/test`), {}));
    await assertFails(getDoc(doc(owner, `users/owner/${collection}/test`)));
  }
  const root = db.collection('users').doc('owner');
  await root.collection('products').doc('product-a').set({ canonicalName: '架空クリーナー' });
  await root.collection('purchaseOrders').doc('order-a').set({ orderedOn: '2026-07-01' });
  await root.collection('purchaseLines').doc('line-a').set({ orderId: 'order-a', productId: 'product-a', quantity: 2, amountMinor: 900, currency: 'JPY' });
  await db.doc('users/other/purchaseOrders/private-order').set({ orderedOn: '2026-07-02' });
  const repository = createFirestoreRepository(db);
  const application = createApplication(repository, () => new Date('2026-10-05T00:00:00Z'));
  assert.equal((await application.getPurchaseHistory('owner')).items.length, 1);
  assert.equal((await application.getPurchaseHistory('other')).items.length, 0);
  const body = { clientMutationId: 'mutation-a', productId: 'product-a', kind: 'state', value: 'spare_available' };
  const results = await Promise.all([application.recordState('owner', body, 'request-a'), application.recordState('owner', body, 'request-b')]);
  assert.deepEqual(results[0], results[1]);
  assert.equal((await root.collection('userObservations').get()).size, 1);
  assert.equal((await root.collection('auditLogs').get()).size, 1);
  const initialAudit = (await root.collection('auditLogs').get()).docs[0].data();
  assert(initialAudit.changes.every(change => change.before === null));
  for (const field of ['observedAt', 'stateRecordedAt', 'revision', 'state', 'origin', 'suppressUntil']) {
    assert(initialAudit.changes.some(change => change.field === field));
  }
  assert.equal(results[0].effectiveState.suppressUntil, '2026-10-12T00:00:00.000Z');
  await assert.rejects(application.recordState('owner', { ...body, value: 'out_of_stock' }, 'request-c'), e => e.code === 'CONFLICT');
  await application.recordState('owner', { ...body, clientMutationId: 'old-observation', value: 'out_of_stock', observedAt: '2026-09-01T00:00:00Z' }, 'request-d');
  assert.equal((await root.collection('productStates').doc('product-a').get()).data().state, 'spare_available');
  await assert.rejects(application.recordState('other', body, 'request-e'), e => e.code === 'NOT_FOUND');
  assert.equal((await db.collection('users').doc('other').collection('auditLogs').get()).size, 0);
  await promisify(execFile)(process.execPath, ['seed-emulator.mjs'], { env: { ...process.env, GOOGLE_CLOUD_PROJECT: 'demo-portal' } });
  const seedToken = await readFile(new URL('../.emulator-id-token', import.meta.url), 'utf8');
  const api = createApi({ application, verifyToken: token => auth.verifyIdToken(token, true), allowedUids: ['fixture-owner'], allowedOrigins: ['http://localhost:5173'] });
  api.listen(0, '127.0.0.1'); await once(api, 'listening');
  t.after(() => new Promise(resolve => { api.close(resolve); api.closeAllConnections(); }));
  const apiUrl = `http://127.0.0.1:${api.address().port}`;
  const response = await fetch(apiUrl + '/purchase-history', { headers: { Authorization: 'Bearer ' + seedToken } });
  assert.equal(response.status, 200);
  const history = await response.json(); assert.equal(history.items[0].line.amountMinor, 900);
  assert.equal(history.items[0].line.quantity, 2);
  const mutation = await fetch(apiUrl + '/user-observations', { method: 'POST', headers: { Authorization: 'Bearer ' + seedToken, 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
  assert.equal(mutation.status, 200);
  assert.equal((await mutation.json()).effectiveState.state, 'spare_available');
});
