import test from 'node:test';
import assert from 'node:assert/strict';
import { initializeApp, deleteApp } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';
import { createCsvImporter, identity } from '../amazon-csv.mjs';
import { createReplenishmentOperations } from '../replenishment.mjs';
import { csvFixture } from './csv-fixture.mjs';

test('CSV -> strong product match -> live estimates, retries, correction and cancellation', async t => {
  assert(process.env.FIRESTORE_EMULATOR_HOST);
  const app = initializeApp({ projectId: 'demo-portal' }, 'replenishment-integration');
  const db = getFirestore(app); t.after(() => deleteApp(app));
  const uid = 'replenishment-owner', root = db.collection('users').doc(uid);
  const importCsv = createCsvImporter(db), operations = createReplenishmentOperations(db, () => new Date('2026-10-05T00:00:00Z'));
  const first = csvFixture('period-first');
  first.order.orderedOn = first.order.lines[0].orderedOn = '2026-08-01'; first.order.lines[0].orderDateEvidence = '2026-08-01T00:00:00Z';
  const second = csvFixture('period-second');
  second.order.externalOrderId = 'FAKE-SECOND';
  second.order.orderKey = identity('order', 'amazon', second.source.accountKey, second.order.externalOrderId);
  second.order.lines[0].orderKey = second.order.orderKey;
  second.order.lines[0].lineMatchKey = identity('amazon_csv_line_hint', second.order.orderKey, 'FAKE-SKU-0');
  second.order.orderedOn = second.order.lines[0].orderedOn = '2026-09-01'; second.order.lines[0].orderDateEvidence = '2026-09-01T00:00:00Z';
  const a = await importCsv(uid, first, 'first'), b = await importCsv(uid, second, 'second');
  const results = await Promise.all([operations.matchProducts(uid, 'match-a'), operations.matchProducts(uid, 'match-b')]);
  assert.equal(results.reduce((sum, r) => sum + r.createdProducts, 0), 1);
  assert.equal((await root.collection('products').get()).size, 1);
  const product = (await root.collection('products').get()).docs[0];
  assert.equal(product.data().replenishmentStatus, 'candidate');
  let estimates = await operations.getReplenishment(uid);
  assert.equal(estimates.items[0].calculation.medianIntervalDays, 31); assert(estimates.items[0].candidate.eligible);
  const audits = (await root.collection('auditLogs').get()).size;
  assert.equal((await operations.matchProducts(uid, 'repeat')).matchedLines, 0);
  assert.equal((await root.collection('auditLogs').get()).size, audits);
  await root.collection('purchaseLines').doc(a.lineIds[0]).update({ userOverrides: { productId: { value: null, observationId: 'explicit-unmatch' } } });
  await operations.matchProducts(uid, 'user-unmatch');
  estimates = await operations.getReplenishment(uid); assert.equal(estimates.items[0].calculation.intervalCount, 0);
  await root.collection('purchaseLines').doc(a.lineIds[0]).update({ userOverrides: {} });
  await root.collection('purchaseLines').doc(b.lineIds[0]).update({ status: 'cancelled' });
  estimates = await operations.getReplenishment(uid); assert(!estimates.items[0].candidate.eligible);
  assert.equal((await operations.getReplenishment('unrelated-owner')).items.length, 0);
  await assert.rejects(operations.matchProducts('../other', 'reject'), e => e.code === 'FORBIDDEN');
});
